
title:  BIENVENIDOS 

subtitlo:  
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
  
  
author: Melany Mero 



email:   melanymero7@gmail.com 


avatar:   https://avatars3.githubusercontent.com/u/57650599?s=460&v=4


 
# Querr√° personalizar url y baseurl para su propio sitio:
baseurl: "/jekyll-theme-prologue" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe

twitter_url:  https://twitter.com/15Melanymero
facebook_url:  https://www.facebook.com/melany.mero.9
instagram_url:  https://www.instagram.com/melany14.mero/?hl=es-la
github_url:


# Google Analytics Tracking ID goes here:
google_analytics:

# The following settings are NECESSARY for the Prologue theme to run:
theme: jekyll-theme-prologue
collections: [sections]
